name: formatter
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: formater
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Black Code Formatter
        uses: lgeiger/black-action@v1.0.1
